### ISSUE TITLE
Is this template still working?

### ISSUE THREAD

**Issue by xolott** [luckyorange/integration-google-tag-manager#2]
I enabled this integration on multiple subdomains (with cors enabled), and I have two problems:

- If I visit `subA.example.com` I get 404 on this address: `https://settings.luckyorange.com/MY_SITE_ID`
- Next, I visit `subB.example.com`, and I get a CORS error: 
```
Access to fetch at 'https://settings.luckyorange.com/MY_SITE_ID' from origin 
'https://subB.example.com' has been blocked by CORS policy: 
The 'Access-Control-Allow-Origin' header has a value 'https://subA.example.com' that is not
equal to the supplied origin. Have the server send the header with a valid value, or, 
if an opaque response serves your needs,  set the request's mode to 'no-cors' to fetch 
the resource with CORS disabled.
```
Plus, a 404 error on this address `https://settings.luckyorange.com/MY_SITE_ID`. Also, the supplied origin is correctly set to `https://subB.example.com`.
- Next, I reload the same page and only get the 404 error.

One of my subdomains, let's call it `subC.example.com` is using the snippet provided by lucky orange directly on the code, and it's working without any issue. It uses the js file `https://d10lpsik1i8c69.cloudfront.net/w.js` instead of `https://tools.luckyorange.com/core/lo.js` used by this integration

Is this template still working, and do I need to do something else? Or I just need to follow the instructions provided by Lucky Orange [here](http://help.luckyorange.com/article/104-how-to-install-in-google-tag-manager), or in [this video](https://www.youtube.com/watch?v=_oHwueKhHyw).

**Comment by hgascoigne** [comment]
Hi there 👋. Since you are receiving a 404 for your site ID at the settings endpoint, my initial guess is that your site might exist in [Lucky Orange Classic](https://classic.luckyorange.com) rather than the new version of our platform. This GTM template only works with the new version of Lucky Orange. There is an [unofficial template](https://tagmanager.google.com/gallery/#/owners/luratic/templates/LuckyOrange) that can be used for the classic version.

If you _are_ on the new Lucky Orange, please send me an email at hayden@luckyorange.com with your site ID and website domain and I would be happy to look into your specific case. Thanks!

**Comment by xolott** [comment]
Thanks @hgascoigne 

It would be great if the template or the docs had a disclaimer about which "version" of Lucky Orange this template is compatible with.

It worked after I changed the tag on GTM to the correct snippet.

**Comment by hgascoigne** [comment]
Glad to see you got it working! That's good feedback and I'll return that back to the team so we can clarify the difference for future users.
